version: "3"

services:
  elibraryws:
    build:
      context: .
      dockerfile: Dockerfile
    image: elibrary:latest
    container_name: elibrary
    ports:
      - "8004:8004"
    volumes:
      - ./app:/code
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres_elibrary

  postgres_elibrary:
    image: postgres:latest
    container_name: pg_elibrary
    restart: always
    env_file:
      - ./app/.env
    ports:
      - "8003:8003"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*' -c port=8003

volumes:
  postgres_data: